# Generated by Django 3.1.2 on 2020-10-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='Just saying Hi !', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='General post', max_length=50),
        ),
    ]
